config/routes.rb
Rails.application.routes.draw do
  root 'application#home'

  get 'static_pages/about'
  get 'static_pages/nutrition_counseling'
  get 'static_pages/cooking_classes'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  resources :users
  resources :appointments
  resources :recipes

  post '/appointments/get_availability' => 'appointments#get_availability'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user

  validates :date, uniqueness: true, presence: true
end

app/models/concerns/time_conversion.rb
module TimeConversion
  #converts a 9-5 day in standard time to military or vice versa;
  #returns military time as a number, standard time as a string w/AM or PM
  #pass in 'standard' (or anything) to convert from military to standard
  def convert_hour(hour, convert_to = 'military')    
    if convert_to == 'military'
      hour < 9 ? (hour + 12) : (hour)
    else
      return '12:00 (noon)' if hour == 12
      hour < 12 ? "#{hour}:00 AM" : "#{hour - 12}:00 PM"
    end
  end
  
  #formats, e.g., '3/09/2019 16:00' => 'Tuesday March 9th, 2019 at 4 PM'
  def format_date(date)
    year, month, day, day_name, hour = [
      date.year,
      Date::MONTHNAMES[date.month],
      date.day.ordinalize,
      date.strftime("%A"),
      convert_hour(date.hour, 'standard')
    ]

    "#{day_name} #{month} #{day}, #{year} at #{hour}"
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :name, uniqueness: :true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :appointments, dependent: :destroy

  validates :first_name, :last_name, :email, :password, presence: true
  validates :email, uniqueness: true
  validates :password, length: { minimum: 8 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?
  
  def home
  end

  def current_user
    session[:user_id] ? @current_user ||= User.find(session[:user_id]) : @current_user = nil
  end

  def logged_in?
    !!current_user
  end

  def redirect_if_logged_in
    redirect_to root_path if logged_in?
  end

end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  include TimeConversion
  
  def new
    redirect_to root_path unless logged_in?
    @appointment = Appointment.new
  end

  def create
    date = get_date_from_params
    appointment = Appointment.create(user_id: current_user.id, date: date)
    appointment_details = { user: current_user, appointment_date: human_readable_date }

    if appointment.valid?  
      respond_to do | format |
        human_readable_date = format_date(date)

        #mail both Shalani and the user about upcoming appointment
        UserMailer.with(appointment_details).appointment_email.deliver_later
        ShalaniMailer.with(appointment_details).appointment_email.deliver_later
  
        format.html { redirect_to(current_user, notice: 'User was successfully created.') }
        format.json { render json: current_user, status: :created, location: current_user }
      end
    end
  end

  def destroy
    Appointment.find(params[:id]).destroy
    redirect_to current_user
  end

  def get_availability
    #temporary
    params.select { | key, _ | :year || :month || :day }.permit!

    #DateTime.new(year, month, day, hour, minute = 0, second = 0, timezone = '-0400')
    chosen_day = DateTime.new(params[:year].to_i, params[:month].to_i, params[:day].to_i)

    range = (chosen_day.beginning_of_day + 9.hours)..(chosen_day.end_of_day - 6.hours)

    render json: Appointment.where(date: range).pluck(:date)
  end

  private

    def get_date_from_params
      year, month, day, hour = [ 
        params[:year], 
        params[:month], 
        params[:day], 
        convert_hour(params[:hour].to_i, convert_to = 'military')
      ].map(&:to_i)
  
      DateTime.new(year, month, day, hour, 0, 0)
    end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_if_logged_in
    @user = User.new
  end

  def create
    @user = User.find_by(email: session_params[:email])
    session[:user_id] = @user.id if @user && @user.authenticate(session_params[:password])

    if !!session[:user_id]
      redirect_to root_path
    else
      @user = User.new(email: session_params[:email])
      flash[:error] = "Username and password don't match"
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end

  private

  def session_params
    params.require(:user).permit(:password, :email, :uid)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def nutrition_counseling
  end

  def cooking_classes
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include TimeConversion

  def new
    redirect_if_logged_in
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    #incorporate this into initializer later
    cell = @user.cell.delete('- ')
    @user.cell = "#{cell[0..2]}-#{cell[3..5]}-#{cell[6..9]}"

    respond_to do | format |
      if @user.save
        session[:user_id] = @user.id

        # Tell the UserMailer to send a welcome email after save
        UserMailer.with(user: @user).welcome_email.deliver_later
 
        format.html { redirect_to(@user, notice: 'User was successfully created.') }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    redirect_to user_path(current_user.id) if current_user.id != params[:id].to_i

    @future_appointments = current_user.appointments.select { | appt | appt.date.future? }.sort_by(&:date)
    @user = current_user
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :home_phone, :cell, :password, :email, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include TimeConversion 
  
  def title(page_name)
    content_for(:title) { page_name }
  end

  def image_tag_link(image_path, target_link, options={})
    link_to(image_tag(image_path, options), target_link)
  end

end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/home.html.erb
<% title("Home") %>

<p class='intro'> 
  Shalani helps you take charge of and improve your life through dietary and nutritional changes. With a little bit of information and a bit of extra help, most patients find themselves significantly happier with their lives and feeling good about themselves and their physical selves.
</p>

<div class="container" id="food_thumbs">
    <div class="vertical"> <%= image_tag 'food/thumbnails/beet-salad-thumb.webp', alt: 'Beet Salad' %> </div>
    <div class="horizontal"> <%= image_tag_link('food/thumbnails/2-thumb.webp', '/recipes/2', { alt: 'Apple Bean Cucumber Salad' }) %> </div>
    <div class="big"> <%= image_tag 'food/thumbnails/strawberries-pomegranate-blueberries-grapes-thumb.webp', alt: 'Strawberries, pomegranate and blueberries' %> </div>
    <div class="vertical"> <%= image_tag 'food/thumbnails/potato-salad-thumb.webp', alt: 'Potato Salad' %> </div>
    <div class="horizontal"> <%= image_tag_link('food/thumbnails/bread-thumb.webp', '/recipes/3', { alt: 'bread' }) %> </div>
    <div class="vertical"> <%= image_tag 'food/thumbnails/berries-cereal-thumb.webp', alt: 'Berries in Cereal' %> </div>
    <div class='big'> <%= image_tag 'food/thumbnails/blueberries-thumb.webp', alt: 'Blueberries and strawberries' %> </div>
    <div class="big"> <%= image_tag 'food/thumbnails/bean-rice-avocado-salad-thumb.webp', alt: 'Bean, rice and avocado salad' %> </div>
    <div class='horizontal'>  <%= image_tag 'food/thumbnails/bean-onion-apple-avocado-salad-thumb.webp', alt: 'Bean, onion, apple and avocado salad' %> </div>
    <div class="horizontal"> <%= image_tag 'food/thumbnails/beet-salad2-thumb.webp', alt: 'Beat salad' %> </div>
    <div class="big"> <%= image_tag 'food/thumbnails/6-thumb.webp', alt: 'Avocado, cucumber, tomato and bean salad' %> </div>    
    <div class="big"> <%= image_tag_link('food/thumbnails/curried-rice-thumb.webp', '/recipes/1', { alt: 'Curried Rice' }) %> </div>
    <div class='big'> <%= image_tag 'food/thumbnails/potatoes-parsley-thumb.webp', alt: 'Seasoned potatoes with parsley' %> </div>
    <div class="vertical"><%= image_tag 'food/thumbnails/strawberries-thumb.webp', alt: 'Strawberry dessert' %> </div>
    <div class="vertical"> <%= image_tag 'food/thumbnails/7-thumb.webp', alt: 'Tomato, basil and avocado salad' %> </div>
</div>

<p class = 'intro'> 
  Shalini offers cooking classes, registered dietitian consultation, accepts all major forms of health insurance
</p>

<div id='locations' style = 'text-align: center;'>
  
  <div class='address'>
    <div class='location-header'>Location</div>
    <div> 390 Woburn St. </div>
    <div> Lexington, MA 02420 </div>
    <div> Phone: 781-330-9928 </div>
  </div>
  <br>
</div>

app/views/appointments/new.html.erb
<%= title('Make an Appointment') %>

<div id="myModal" class="modal">
  <div class="modal-content">
    <!--form and close button added in JS-->
  </div>
</div>

<%= month_calendar do | date | %>
  <%= date.day %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class = 'bg-foot'>
  <div class="container">
    <div id='foot-txt'> 
      © Shalini 2019 
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<div class='bg-head'>
  <div id='header-title'> Eat Well </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="nav">
  <input type="checkbox" id="nav-check">
  <div class="nav-header">
    <div class="nav-title">
      <%= link_to 'Lexington Nutrition', '/' %>
    </div>
  </div>

  <% if logged_in? %>
   <span class='greeting'> 
     <%= "Welcome, #{current_user.first_name}!"%> 
   </span>
  <% end %>

  <div class="nav-btn">
    <label for="nav-check">
      <span></span>
      <span></span>
      <span></span>
    </label>
  </div>
  
  <div class="nav-links">
    <%= link_to 'About Shalini', static_pages_about_path %>  
    <a href="#">Services</a>
    <%= link_to 'Sign Up', '/signup' unless logged_in? %>
    <%= link_to 'Log In', '/login' unless logged_in? %>
    <%= link_to 'Make an Appointment', '/appointments/new' if logged_in? %>
    <%= link_to 'Recipes', '/recipes' %>
    <%= link_to 'You', user_path(current_user) if logged_in? %>
    <%= link_to 'Log Out', '/logout', method: :delete if logged_in? %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='en'>
  <head>
    <title> 
      <%= content_for?(:title) ? yield(:title) : 'Shalini Health' %> 
    </title>

    <meta charset="utf-8">
    <meta name="description" content="Shalini, Registered Dietitian Consulting Services">
    <meta name="viewport" content="width=950, initial-scale=0.4">

    <%= favicon_link_tag asset_path('health.ico'), rel: 'icon', type: 'image/x-icon' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Dancing+Script:400|Josefin+Sans:100">

    <!-- polyfill for browsers that don't support WebP -->
    <script src="https://unpkg.com/webp-hero@0.0.0-dev.23/dist-cjs/webp-hero.bundle.js" defer></script>

    <script> 
      document.addEventListener('turbolinks:load', function() {
        const webpMachine = new webpHero.WebpMachine()
        webpMachine.polyfillDocument()
      });
    </script>
  </head>

  <body>
    
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>

  </body>
</html>

app/views/recipes/index.html.erb
<% title('Recipes') %>

<div>

  <% @recipes.each do | recipe | %>
    <ul> 
      <%= image_tag "food/thumbnails/#{recipe.image_name}-thumb.webp", class: 'index-thumb' %> 
      <%= link_to recipe.name, recipe_path(recipe), class: 'recipe-link' %> 
    </ul>
  <% end %>

</div>

app/views/recipes/show.html.erb
<% title(@recipe.name) %>

<body class='recipe-body'>

  <div id='recipe-page'>
    <div class='row'>
      <div class="recipe-column text-center" id='recipe-description'>
        <h1 class='title' id='description-title'>Description</h1>
        <p id='description-body'> <%= @recipe.description %> </p>
      </div>

      <div class='recipe-column text-center'> 
        <h1 class='title' id='dish-title'> 
          <%= @recipe.name %> 
        </h1>
        <%= image_tag "food/#{@recipe.image_name}.webp", id: 'recipe-picture' %> 
      </div>

      <div class='recipe-column text-center' id='recipe'>
        <h1 class='title'>Recipe</h1>

        <% @recipe.ingredients.each do | ingredient | %>
          <p class='ingredient'> <%= ingredient %> </p>
        <% end %>
        
        <div class='heading'>
          <h2 class='title' id='instructions'>Instructions</h2>
          <ol>
            <% @recipe.directions.lines.each do | instruction_step | %>
              <li class='instruction'> <%= instruction_step %> </li>
            <% end %>
          </ol>
        </div>

        <h2 class='title' id='prep-time-title'>Estimated prep time:</h2>
        <p id='prep-time'> <%= @recipe.prep_time %> </p>
      </div>
      
    </div>
  </div>

</body>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: "&larr; Prev".html_safe), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next &rarr;'.html_safe), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/static_pages/about.html.erb
<%= title('About Shalani')%>

<div id='bio-heading'>
  <h1> About Shalini </h1>
  <%= image_tag 'shalani-photo', id: 'shalani-headshot', alt: 'shalini-photo' %>
  <h2> Shalani MS, MEd, RDN, LDN, CDE </h2>
  <p>Shalani has a passion for gardening. She loves to cook and try recipes from all over the world.</p>
</div>

<div id='bio'>
  <h3>Background</h3>

  <div id='education' class='indent'>
    <h4>Education</h4>
    <p class='indent'>&bull; M.S. & MEd, Penn State University </p>
    <p class='indent'>&bull; B.S. Nutrition & Home Ec, Punjab University, India</p>
    <p class='indent'>&bull; Certified Diabetes Educator, NCBDE</p>
  </div>

  <div class='dietitician-info'>
    <div id='languages' class='indent'>
      <h4>Languages</h4>
      <p class='indent'>&bull; English</p>
      <p class='indent'>&bull; Hindi </p>
      <p class='indent'>&bull; Urdu </p>
      <p class='indent'>&bull; Bengali </p>
    </div>
    
    <div id='interests' class='indent bottom'> 
      <h4>Focuses: </h4>
      <p class='indent'>&bull; Diabetes education</p>
      <p class='indent'>&bull; Women’s health</p>
      <p class='indent'>&bull; Pediatrics</p>
      <p class='indent'>&bull; Weight management</p>
    </div>
  </div>

</div>

app/views/static_pages/cooking_classes.html.erb
<% title('Cooking Classes') %>

app/views/static_pages/nutrition_counseling.html.erb
<% title('Nutrition Counseling') %>

app/views/users/new.html.erb
<%= form_for @user do | f | %>

  <%= f.label :first_name %>
  <%= f.text_field :first_name %> 
  <br>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %> 
  <br>
  <%= f.label :email %>
  <%= f.text_field :email %> 
  <br>
  <%= f.label :contact_number %>
  <%= f.telephone_field :cell, pattern: "^[0-9]{3}[- ]{0,1}[0-9]{3}[- ]{0,1}[0-9]{4}$", required: true, placeholder: '781-555-1234' %>
  <br>
  <%= f.label :password %>
  <%= f.password_field :password %> 
  <br>
  <%= f.label :password_confirmation  %>
  <%= f.password_field :password_confirmation  %> 
  <br>
  <br>
  <%= f.submit %>
  
<% end %>

app/views/users/show.html.erb
<div class='text-center'>

  <h1> Hi, <%= @user.first_name %>! </h1>

  <% unless @future_appointments.empty? %>

    <h3> 
      You have <%= @future_appointments.size %> upcoming <%= @future_appointments.size > 1 ? 'appointments' : 'appointment' %>:
    </h3>

    <% @future_appointments.each do | appointment | %>
      <h4> 
        <%= format_date(appointment.date) %> 

        <% if (appointment.date - 24.hours).future? %>          
          <%= button_to "Cancel Appointment", appointment, class: :button, method: :delete, data: { confirm: "Delete appointment on #{appointment.date}?" } %>
        <% end %>
      </h4>
    <% end %>

  <% end %>

</div>